---
- hosts: webservers
  become: true

  tasks:
    - name: install apache2
      ansible.builtin.apt:
        name: apache2
        state: present
    - name: copy the modified index file
      ansible.builtin.template:
        src: index.html.j2
        dest: /var/www/html/index.html
        mode: 0644
    - name: modify apache2 config to listen on port 8080 ports config
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: "^Listen 80"
        line: "Listen 8080"
        state: present
    - name: modify default config to listen to port 8080
      lineinfile:
        path: /etc/apache2/sites-enabled/000-default.conf
        regexp: '^<VirtualHost \*:80>'
        line: '<VirtualHost *:8080>'
        state: present
    - name: startd and enable apache2
      service:
        name: apache2
        enabled: true
        state: started 
